Changed the styling of github button
hotwax/omnichannelcto-site pull request #10
Opened 2022-10-14 08:11 UTC by snehafarkya

Hey! I have upgraded the styling of the GitHub button. 

Kindly view it and accept it.

2022-10-14 09:55 UTC, dt2patel commented
Related issue is not requested, PR can be accepted for using flex instead of grid, but still need to consider below points.

A few things to think about @snehafarkya:
Code indentation?
What is the default flex direction?

2022-10-14 10:06 UTC, snehafarkya commented
Ohh sure. Can you review it now?

2022-10-17 04:15 UTC, dt2patel requested changes
almost ready to merge. please see comments

2022-10-17 04:15 UTC, dt2patel commented on index.html
>      grid-gap: 8px;
Need to update property to "gap" since we are not using grid anymore

2022-10-17 04:15 UTC, dt2patel commented on index.html
> +    border-radius: 12px;
remove border radius and padding to maintain original styling.

2022-10-17 04:15 UTC, dt2patel commented on index.html
> +
remove extra space.

2022-11-10 10:24 UTC, closed without merging